"""Extract Alex Chen's writing voice from the corpus — port of scripts/extract-voice.ts.

  python apps/agent-py/scripts/extract_voice.py
Output: scripts/fixtures/alex-voice.md
"""
from __future__ import annotations

import asyncio
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # apps/agent-py

from app.config import is_llm_configured, is_mongo_configured  # noqa: E402
from app.db.mongo import documents  # noqa: E402
from app.llm.genai_client import generate  # noqa: E402

ALEX_EMAIL = "alex.chen@northwind.dev"
SAMPLE_SIZE = 24
_OUT = Path(__file__).resolve().parents[3] / "scripts" / "fixtures" / "alex-voice.md"


async def pick_sent_emails() -> list[dict]:
    flt = {
        "source": "email",
        "$or": [
            {"metadata.from": {"$regex": ALEX_EMAIL, "$options": "i"}},
            {"metadata.from": {"$regex": "alex chen", "$options": "i"}},
            {"metadata.direction": "from_alex"},
        ],
    }
    rows = await documents().find(flt, limit=SAMPLE_SIZE * 3).to_list(length=None)
    out = []
    for d in rows[:SAMPLE_SIZE]:
        md = d.get("metadata") or {}
        out.append({
            "title": d.get("title") if isinstance(d.get("title"), str) else "",
            "body": d.get("body") if isinstance(d.get("body"), str) else "",
            "to": md.get("to") if isinstance(md.get("to"), list) else [],
            "date": md.get("date") if isinstance(md.get("date"), str) else None,
        })
    return out


async def summarize_voice(samples: list[dict]) -> str:
    if not samples:
        return "No outbound emails were found in the corpus. The default voice cue will be used."
    corpus = "\n\n".join(
        f"--- email {i + 1} ---\nSubject: {s['title']}\nTo: {', '.join(s['to'])}\nDate: {s['date'] or ''}\n\n{s['body']}"
        for i, s in enumerate(samples))
    prompt = f"""You are analyzing the writing voice of a senior PM named Alex Chen, drawn from {len(samples)} of his outbound emails.

Read the samples below carefully. Then produce a short, USEFUL style guide that another LLM can follow to draft new emails that sound like Alex. Be CONCRETE — quote real phrasings, name real tics, list openings and sign-offs he actually uses. Avoid generic advice.

Return markdown with these sections:
## Voice fingerprint
3–6 bullets capturing the distinctive flavor (sentence rhythm, register, formality).

## Openings he uses
3–6 short example openings, verbatim where possible.

## Closings & sign-offs
2–4 examples, verbatim.

## Phrases he favors
8–14 short phrases (≤6 words each) lifted from the samples. One per line, with leading "- ".

## Phrases he avoids
4–8 patterns that would feel WRONG coming from him.

## Length & shape
1–2 sentences on email length and paragraph rhythm.

Samples:
{corpus}"""
    r = await generate(prompt, temperature=0.4, max_tokens=8192, thinking_budget=0)
    return r.text


async def main() -> None:
    if not is_mongo_configured():
        print("MONGODB_URI is required", file=sys.stderr)
        sys.exit(1)
    if not is_llm_configured():
        print("no LLM provider configured — set LLM_PROVIDER + credentials", file=sys.stderr)
        sys.exit(1)
    print(f"[voice] sampling outbound emails (target={SAMPLE_SIZE})…")
    samples = await pick_sent_emails()
    print(f"[voice] got {len(samples)} samples")
    print("[voice] summarizing…")
    md = await summarize_voice(samples)

    _OUT.parent.mkdir(parents=True, exist_ok=True)
    header = (f"<!-- generated by scripts/extract_voice.py on {datetime.now(timezone.utc).isoformat()} -->\n"
              f"<!-- sampled {len(samples)} outbound emails from {ALEX_EMAIL} -->\n\n")
    _OUT.write_text(header + md.strip() + "\n", encoding="utf-8")
    print(f"[voice] wrote → {_OUT}")


if __name__ == "__main__":
    asyncio.run(main())
